// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using etraducao.Data;

namespace etraducao.Migrations
{
    [DbContext(typeof(EtraducaoContexto))]
    [Migration("20200209043558_InitContext")]
    partial class InitContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("etraducao.Models.Entidades.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdExterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasName("Unique Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("etraducao.Models.Entidades.ControleDeValores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("ValorDaLauda")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ControleDeValores");
                });

            modelBuilder.Entity("etraducao.Models.Entidades.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Arquivo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantidadeDeCaracteres")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantidadeDeLaudas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SolicitacaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SolicitacaoId");

                    b.ToTable("Documento");
                });

            modelBuilder.Entity("etraducao.Models.Entidades.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BankSlipUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataDeVencimento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DevePostarEncomenda")
                        .HasColumnType("bit");

                    b.Property<string>("FormaDePagamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SolicitacaoId")
                        .HasColumnType("int");

                    b.Property<string>("StatusDePagamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SolicitacaoId")
                        .IsUnique();

                    b.ToTable("Pagamento");
                });

            modelBuilder.Entity("etraducao.Models.Entidades.Solicitacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ApostilaDeHaia")
                        .HasColumnType("bit");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataDaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdiomaDestino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdiomaOrigem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PagamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantidadeDeDocumentosParaApostilar")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeDeDocumentosParaReconhecerFirma")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantidadeDeLaudas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoDeSolicitacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorDaApostilaDeHaia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorDoReconhecimentoDeFirma")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorPorLauda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Solicitacao");
                });

            modelBuilder.Entity("etraducao.Models.Entidades.Cliente", b =>
                {
                    b.OwnsOne("etraducao.Models.ValuesObjects.Cnpj", "Cnpj", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Codigo")
                                .HasColumnName("Cnpj")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Cliente");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.OwnsOne("etraducao.Models.ValuesObjects.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Codigo")
                                .HasColumnName("Cpf")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Cliente");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });
                });

            modelBuilder.Entity("etraducao.Models.Entidades.Documento", b =>
                {
                    b.HasOne("etraducao.Models.Entidades.Solicitacao", "Solicitacao")
                        .WithMany("Documentos")
                        .HasForeignKey("SolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("etraducao.Models.Entidades.Pagamento", b =>
                {
                    b.HasOne("etraducao.Models.Entidades.Solicitacao", "Solicitacao")
                        .WithOne("Pagamento")
                        .HasForeignKey("etraducao.Models.Entidades.Pagamento", "SolicitacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("etraducao.Models.Entidades.Solicitacao", b =>
                {
                    b.HasOne("etraducao.Models.Entidades.Cliente", "Cliente")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
